theme: jekyll-theme-cayman
title: Gemstone.Logging
description: GPA Gemstone Logging Library
github:
  repository_name: gemstone/logging
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
